export interface ComplianceReportData {
  companyName: string;
  generatedAt: string;
  overallScore: number;
  totalRequirements: number;
  compliantCount: number;
  nonCompliantCount: number;
  inProgressCount: number;
  notApplicableCount: number;
  categories: {
    name: string;
    score: number;
    total: number;
    compliant: number;
  }[];
  requirements: {
    name: string;
    category: string;
    status: string;
    isMandatory: boolean;
    description: string;
    lastReviewed: string | null;
  }[];
}

export function generateComplianceReportHTML(data: ComplianceReportData): string {
  const getStatusBadge = (status: string) => {
    const colors: Record<string, string> = {
      COMPLIANT: "#22c55e",
      NON_COMPLIANT: "#ef4444",
      IN_PROGRESS: "#f59e0b",
      NOT_APPLICABLE: "#6b7280",
    };
    return `<span style="background:${colors[status] || "#6b7280"};color:white;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600">${status.replace(/_/g, " ")}</span>`;
  };

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Compliance Report - ${data.companyName}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 40px; color: #1e293b; }
    .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #e2e8f0; }
    .header h1 { margin: 0; font-size: 24px; color: #1e293b; }
    .header p { color: #64748b; margin: 8px 0 0; font-size: 14px; }
    .score-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; text-align: center; margin-bottom: 32px; }
    .score-value { font-size: 48px; font-weight: 700; color: ${data.overallScore >= 80 ? "#22c55e" : data.overallScore >= 50 ? "#f59e0b" : "#ef4444"}; }
    .score-label { font-size: 14px; color: #64748b; margin-top: 4px; }
    .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }
    .stat { background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; text-align: center; }
    .stat-value { font-size: 24px; font-weight: 700; }
    .stat-label { font-size: 12px; color: #64748b; margin-top: 4px; }
    h2 { font-size: 18px; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #e2e8f0; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    th { text-align: left; padding: 12px; background: #f8fafc; border-bottom: 2px solid #e2e8f0; font-size: 12px; color: #64748b; text-transform: uppercase; }
    td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 12px; color: #64748b; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>Compliance Report</h1>
    <p>${data.companyName} | Generated on ${new Date(data.generatedAt).toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}</p>
  </div>

  <div class="score-card">
    <div class="score-value">${data.overallScore}%</div>
    <div class="score-label">Overall Compliance Score</div>
  </div>

  <div class="stats">
    <div class="stat">
      <div class="stat-value" style="color:#22c55e">${data.compliantCount}</div>
      <div class="stat-label">Compliant</div>
    </div>
    <div class="stat">
      <div class="stat-value" style="color:#ef4444">${data.nonCompliantCount}</div>
      <div class="stat-label">Non-Compliant</div>
    </div>
    <div class="stat">
      <div class="stat-value" style="color:#f59e0b">${data.inProgressCount}</div>
      <div class="stat-label">In Progress</div>
    </div>
    <div class="stat">
      <div class="stat-value" style="color:#6b7280">${data.notApplicableCount}</div>
      <div class="stat-label">Not Applicable</div>
    </div>
  </div>

  <h2>Category Breakdown</h2>
  <table>
    <thead><tr><th>Category</th><th>Score</th><th>Compliant</th><th>Total</th></tr></thead>
    <tbody>
      ${data.categories.map(c => `<tr><td>${c.name}</td><td>${c.score}%</td><td>${c.compliant}</td><td>${c.total}</td></tr>`).join("")}
    </tbody>
  </table>

  <h2>Detailed Requirements</h2>
  <table>
    <thead><tr><th>Requirement</th><th>Category</th><th>Status</th><th>Mandatory</th><th>Last Reviewed</th></tr></thead>
    <tbody>
      ${data.requirements.map(r => `<tr><td>${r.name}</td><td>${r.category}</td><td>${getStatusBadge(r.status)}</td><td>${r.isMandatory ? "Yes" : "No"}</td><td>${r.lastReviewed ? new Date(r.lastReviewed).toLocaleDateString("en-IN") : "Never"}</td></tr>`).join("")}
    </tbody>
  </table>

  <div class="footer">
    <p><strong>Disclaimer:</strong> This report is generated by LegalMint AI and does not constitute legal advice. Consult a qualified advocate for compliance matters.</p>
    <p>LegalMint AI | India's AI-Powered Legal Compliance Platform</p>
  </div>
</body>
</html>`;
}

export async function downloadComplianceReport(data: ComplianceReportData) {
  const html = generateComplianceReportHTML(data);
  const blob = new Blob([html], { type: "text/html" });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `compliance-report-${data.companyName.replace(/[^a-zA-Z0-9]/g, "_")}-${new Date().toISOString().split("T")[0]}.html`;
  document.body.appendChild(a);
  a.click();
  window.URL.revokeObjectURL(url);
  document.body.removeChild(a);
}
