import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";

export async function exportToDocx(title: string, content: string): Promise<Buffer> {
  const paragraphs = content.split("\n").map((line) => {
    if (line.startsWith("# ")) {
      return new Paragraph({
        children: [new TextRun({ text: line.replace("# ", ""), bold: true, size: 48 })],
        heading: HeadingLevel.HEADING_1,
        spacing: { after: 200 },
      });
    }
    if (line.startsWith("## ")) {
      return new Paragraph({
        children: [new TextRun({ text: line.replace("## ", ""), bold: true, size: 36 })],
        heading: HeadingLevel.HEADING_2,
        spacing: { after: 160, before: 200 },
      });
    }
    if (line.startsWith("### ")) {
      return new Paragraph({
        children: [new TextRun({ text: line.replace("### ", ""), bold: true, size: 32 })],
        heading: HeadingLevel.HEADING_3,
        spacing: { after: 120, before: 160 },
      });
    }
    if (line.startsWith("- ") || line.startsWith("* ")) {
      return new Paragraph({
        children: [new TextRun({ text: line.replace(/^[-*] /, ""), size: 24 })],
        bullet: { level: 0 },
        spacing: { after: 80 },
      });
    }
    if (line.trim() === "") {
      return new Paragraph({ children: [], spacing: { after: 120 } });
    }
    return new Paragraph({
      children: [new TextRun({ text: line, size: 24 })],
      spacing: { after: 120 },
    });
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            children: [new TextRun({ text: title, bold: true, size: 48 })],
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          ...paragraphs,
          new Paragraph({
            children: [
              new TextRun({
                text: "Disclaimer: This document was generated by LegalMint AI and does not constitute legal advice. Consult a qualified advocate for legal matters.",
                italics: true,
                size: 18,
                color: "666666",
              }),
            ],
            spacing: { before: 600 },
            alignment: AlignmentType.CENTER,
          }),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}

export function exportToHtml(title: string, content: string): string {
  const htmlContent = content
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br>");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; line-height: 1.6; color: #333; }
    h1 { font-size: 2em; border-bottom: 2px solid #eaecef; padding-bottom: 0.3em; }
    h2 { font-size: 1.5em; border-bottom: 1px solid #eaecef; padding-bottom: 0.3em; }
    h3 { font-size: 1.25em; }
    .disclaimer { margin-top: 40px; padding: 16px; background: #f6f8fa; border-radius: 6px; font-size: 0.85em; color: #666; text-align: center; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div>${htmlContent}</div>
  <div class="disclaimer">Disclaimer: This document was generated by LegalMint AI and does not constitute legal advice. Consult a qualified advocate for legal matters.</div>
</body>
</html>`;
}

export function exportToMarkdown(title: string, content: string): string {
  return `# ${title}\n\n${content}\n\n---\n\n*Disclaimer: This document was generated by LegalMint AI and does not constitute legal advice. Consult a qualified advocate for legal matters.*`;
}
