"use client";

import { useState } from "react";
import { createPortal } from "react-dom";

interface DocumentPreviewProps {
  title: string;
  content: string;
  isOpen: boolean;
  onClose: () => void;
}

export function DocumentPreview({ title, content, isOpen, onClose }: DocumentPreviewProps) {
  const [isFullscreen, setIsFullscreen] = useState(false);

  if (!isOpen) return null;

  const formattedContent = content
    .replace(/^# (.+)$/gm, "<h1 class='text-2xl font-bold mb-4'>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2 class='text-xl font-semibold mb-3 mt-6'>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3 class='text-lg font-medium mb-2 mt-4'>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, "<li class='ml-4 list-disc'>$1</li>")
    .replace(/\n\n/g, "</p><p class='mb-3'>")
    .replace(/\n/g, "<br>");

  return createPortal(
    <div
      className={`fixed inset-0 z-50 ${isFullscreen ? "bg-white" : "bg-black/50"} flex items-center justify-center p-4`}
      onClick={onClose}
    >
      <div
        className={`bg-white rounded-xl shadow-2xl ${isFullscreen ? "w-full h-full max-w-none" : "w-full max-w-3xl max-h-[80vh]"} flex flex-col`}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between p-4 border-b">
          <h2 className="text-lg font-semibold text-slate-900 truncate">{title}</h2>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsFullscreen(!isFullscreen)}
              className="p-2 hover:bg-slate-100 rounded-lg text-slate-600"
              title="Toggle fullscreen"
            >
              {isFullscreen ? "✕" : "⛶"}
            </button>
            <button
              onClick={onClose}
              className="p-2 hover:bg-slate-100 rounded-lg text-slate-600"
              title="Close"
            >
              ✕
            </button>
          </div>
        </div>
        <div
          className="flex-1 overflow-y-auto p-6 prose prose-slate max-w-none"
          dangerouslySetInnerHTML={{ __html: `<p class='mb-3'>${formattedContent}</p>` }}
        />
        <div className="p-4 border-t bg-slate-50">
          <p className="text-xs text-amber-700 text-center">
            <strong>Disclaimer:</strong> This document was generated by LegalEase AI and does not constitute legal advice.
          </p>
        </div>
      </div>
    </div>,
    document.body
  );
}
