"use client";

import { useState } from "react";
import { createPortal } from "react-dom";
import { Maximize2, Minimize2, X } from "lucide-react";

interface DocumentPreviewProps {
  title: string;
  content: string;
  isOpen: boolean;
  onClose: () => void;
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export function DocumentPreview({ title, content, isOpen, onClose }: DocumentPreviewProps) {
  const [isFullscreen, setIsFullscreen] = useState(false);

  if (!isOpen) return null;

  const formattedContent = escapeHtml(content)
    .replace(/^# (.+)$/gm, "<h1 class='mb-4 text-2xl font-bold'>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2 class='mb-3 mt-6 text-xl font-semibold'>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3 class='mb-2 mt-4 text-lg font-medium'>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, "<li class='ml-4 list-disc'>$1</li>")
    .replace(/\n\n/g, "</p><p class='mb-3'>")
    .replace(/\n/g, "<br>");

  return createPortal(
    <div
      className={`fixed inset-0 z-50 ${isFullscreen ? "bg-background" : "bg-foreground/40"} flex items-center justify-center p-4 backdrop-blur-sm`}
      onClick={onClose}
    >
      <div
        className={`flex flex-col rounded-lg border border-border bg-card shadow-xl ${isFullscreen ? "h-full w-full max-w-none" : "max-h-[80vh] w-full max-w-3xl"}`}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between gap-3 border-b border-border p-4">
          <h2 className="truncate text-lg font-semibold">{title}</h2>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsFullscreen(!isFullscreen)}
              className="rounded-md p-2 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              title="Toggle fullscreen"
              aria-label="Toggle fullscreen"
            >
              {isFullscreen ? <Minimize2 className="h-4 w-4" /> : <Maximize2 className="h-4 w-4" />}
            </button>
            <button
              onClick={onClose}
              className="rounded-md p-2 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              title="Close"
              aria-label="Close preview"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>
        <div
          className="prose prose-slate max-w-none flex-1 overflow-y-auto p-6 dark:prose-invert"
          dangerouslySetInnerHTML={{ __html: `<p class='mb-3'>${formattedContent}</p>` }}
        />
        <div className="border-t border-border bg-secondary/10 p-4">
          <p className="text-center text-xs text-foreground/70">
            <strong>Disclaimer:</strong> This document was generated by LegalMint AI and does not constitute legal advice.
          </p>
        </div>
      </div>
    </div>,
    document.body
  );
}
