import Link from "next/link";
import { AlertTriangle, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Logo } from "@/components/Logo";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b border-border/50 bg-background/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Logo size="sm" />
            <Link href="/">
              <Button variant="ghost" size="sm">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Home
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="mb-8">
          <Badge variant="default" className="mb-4">Legal</Badge>
          <h1 className="text-3xl sm:text-4xl font-bold text-foreground mb-2">Legal Disclaimer</h1>
          <p className="text-sm text-muted-foreground">Last updated: May 17, 2026</p>
        </div>

        <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-xl p-6 mb-8">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-amber-900 dark:text-amber-100 font-semibold text-lg mb-2">Important Notice</p>
              <p className="text-amber-800 dark:text-amber-200">
                LegalMint AI is NOT a law firm and does NOT provide legal advice. All documents generated by this
                Platform are informational drafts and must be reviewed by a qualified advocate enrolled with the
                Bar Council of India before use.
              </p>
            </div>
          </div>
        </div>

        <div className="space-y-8">
          <Section number="1" title="No Attorney-Client Relationship">
            Use of LegalMint AI does not create an attorney-client relationship. The Platform provides automated
            document generation based on templates and artificial intelligence. No legal advice is given or implied.
          </Section>

          <Section number="2" title="AI-Generated Content">
            Documents are generated using AI models (NVIDIA NIM, Groq) trained on publicly available legal texts.
            AI may produce inaccurate, outdated, or incomplete content. The Platform does not guarantee accuracy,
            completeness, or legal validity of generated documents.
          </Section>

          <Section number="3" title="Mandatory Legal Review">
            <p className="text-muted-foreground mb-4">
              All documents generated by LegalMint AI MUST be reviewed by a qualified legal professional before:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground space-y-1">
              <li>Publishing on your website or application</li>
              <li>Entering into contractual agreements</li>
              <li>Filing with government authorities</li>
              <li>Sharing with employees, customers, or partners</li>
            </ul>
          </Section>

          <Section number="4" title="Jurisdiction Limitation">
            The Platform is designed exclusively for Indian jurisdiction. Documents are based on Indian laws as they
            exist at the time of generation. Laws may change, and the Platform may not reflect the most recent
            amendments, rules, or judicial interpretations.
          </Section>

          <Section number="5" title="Limitation of Liability">
            <p className="text-muted-foreground mb-4">
              LegalMint AI, its founders, employees, and service providers shall not be liable for any damages,
              losses, penalties, or legal consequences arising from:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground space-y-1">
              <li>Use of AI-generated documents without legal review</li>
              <li>Reliance on compliance tracking information</li>
              <li>Failure to comply with applicable laws</li>
              <li>Errors, omissions, or inaccuracies in generated content</li>
              <li>Changes in law after document generation</li>
            </ul>
          </Section>

          <Section number="6" title="Compliance Responsibility">
            You are solely responsible for ensuring your business complies with all applicable Indian laws and
            regulations. The Platform&apos;s compliance tracking is a tool and does not replace professional
            compliance advice from a Chartered Accountant, Company Secretary, or legal counsel.
          </Section>

          <Section number="7" title="Third-Party Services">
            The Platform integrates with third-party services (Supabase, Cashfree, Resend, NVIDIA, Groq). We are
            not responsible for the practices, terms, or reliability of these services.
          </Section>

          <Section number="8" title="Professional Consultation">
            <p className="text-muted-foreground mb-4">We strongly recommend consulting:</p>
            <ul className="list-disc pl-6 text-muted-foreground space-y-1">
              <li>An <strong className="text-foreground">advocate</strong> for legal documents and compliance</li>
              <li>A <strong className="text-foreground">Chartered Accountant (CA)</strong> for tax and GST matters</li>
              <li>A <strong className="text-foreground">Company Secretary (CS)</strong> for corporate compliance</li>
            </ul>
          </Section>

          <Section number="9" title="Acknowledgment">
            By using LegalMint AI, you acknowledge that you have read and understood this disclaimer and agree that
            the Platform does not provide legal advice.
          </Section>
        </div>
      </main>

      <footer className="border-t border-border/50 py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <p className="text-sm text-muted-foreground text-center">
            &copy; 2026 LegalMint AI. Not a substitute for legal advice. Consult a qualified advocate.
          </p>
        </div>
      </footer>
    </div>
  );
}

function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="flex items-center gap-3 mb-4">
        <span className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center text-sm font-semibold">
          {number}
        </span>
        <h2 className="text-xl font-semibold text-foreground">{title}</h2>
      </div>
      <div className="text-muted-foreground leading-relaxed pl-11">{children}</div>
    </div>
  );
}
