import Link from "next/link";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="flex items-center gap-2">
              <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-sm">L</span>
              </div>
              <span className="font-bold text-xl text-slate-900">LegalEase AI</span>
            </Link>
            <Link href="/" className="text-sm text-slate-600 hover:text-slate-900">
              Back to Home
            </Link>
          </div>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Legal Disclaimer</h1>
        <p className="text-sm text-slate-500 mb-8">Last updated: May 17, 2026</p>

        <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-8">
          <p className="text-amber-900 font-semibold text-lg mb-2">⚠️ Important Notice</p>
          <p className="text-amber-800">
            LegalEase AI is NOT a law firm and does NOT provide legal advice. All documents generated by this
            Platform are informational drafts and must be reviewed by a qualified advocate enrolled with the
            Bar Council of India before use.
          </p>
        </div>

        <div className="prose prose-slate max-w-none">
          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">1. No Attorney-Client Relationship</h2>
          <p className="text-slate-700 mb-4">
            Use of LegalEase AI does not create an attorney-client relationship. The Platform provides automated
            document generation based on templates and artificial intelligence. No legal advice is given or implied.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">2. AI-Generated Content</h2>
          <p className="text-slate-700 mb-4">
            Documents are generated using AI models (NVIDIA NIM, Groq) trained on publicly available legal texts.
            AI may produce inaccurate, outdated, or incomplete content. The Platform does not guarantee accuracy,
            completeness, or legal validity of generated documents.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">3. Mandatory Legal Review</h2>
          <p className="text-slate-700 mb-4">
            All documents generated by LegalEase AI MUST be reviewed by a qualified legal professional before:
          </p>
          <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-1">
            <li>Publishing on your website or application</li>
            <li>Entering into contractual agreements</li>
            <li>Filing with government authorities</li>
            <li>Sharing with employees, customers, or partners</li>
          </ul>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">4. Jurisdiction Limitation</h2>
          <p className="text-slate-700 mb-4">
            The Platform is designed exclusively for Indian jurisdiction. Documents are based on Indian laws as they
            exist at the time of generation. Laws may change, and the Platform may not reflect the most recent
            amendments, rules, or judicial interpretations.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">5. Limitation of Liability</h2>
          <p className="text-slate-700 mb-4">
            LegalEase AI, its founders, employees, and service providers shall not be liable for any damages,
            losses, penalties, or legal consequences arising from:
          </p>
          <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-1">
            <li>Use of AI-generated documents without legal review</li>
            <li>Reliance on compliance tracking information</li>
            <li>Failure to comply with applicable laws</li>
            <li>Errors, omissions, or inaccuracies in generated content</li>
            <li>Changes in law after document generation</li>
          </ul>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">6. Compliance Responsibility</h2>
          <p className="text-slate-700 mb-4">
            You are solely responsible for ensuring your business complies with all applicable Indian laws and
            regulations. The Platform&apos;s compliance tracking is a tool and does not replace professional
            compliance advice from a Chartered Accountant, Company Secretary, or legal counsel.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">7. Third-Party Services</h2>
          <p className="text-slate-700 mb-4">
            The Platform integrates with third-party services (Supabase, Cashfree, Resend, NVIDIA, Groq). We are
            not responsible for the practices, terms, or reliability of these services.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">8. Professional Consultation</h2>
          <p className="text-slate-700 mb-4">
            We strongly recommend consulting:
          </p>
          <ul className="list-disc pl-6 text-slate-700 mb-4 space-y-1">
            <li>An <strong>advocate</strong> for legal documents and compliance</li>
            <li>A <strong>Chartered Accountant (CA)</strong> for tax and GST matters</li>
            <li>A <strong>Company Secretary (CS)</strong> for corporate compliance</li>
          </ul>

          <h2 className="text-xl font-semibold text-slate-900 mt-8 mb-4">9. Acknowledgment</h2>
          <p className="text-slate-700 mb-4">
            By using LegalEase AI, you acknowledge that you have read and understood this disclaimer and agree that
            the Platform does not provide legal advice.
          </p>
        </div>
      </main>

      <footer className="border-t py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <p className="text-sm text-slate-500 text-center">
            © 2026 LegalEase AI. Not a substitute for legal advice. Consult a qualified advocate.
          </p>
        </div>
      </footer>
    </div>
  );
}
